name: Gradle Build & Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew build
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle Test
        run: |
          ./gradlew test

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

#      - name: SonarQube Scan
#        uses: kitabisa/sonarqube-action@v1.2.0
#        with:
#          host: ${{ secrets.SONARQUBE_HOST }}
#          login: ${{ secrets.SONARQUBE_TOKEN }}

#      - name: Sonarqube analyze
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          ./gradlew sonarqube  \
#              -PSONAR_HOST=https://sonarcloud.io/  \
#              -PSONAR_TOKEN=68b70ce25b70df213fde891f59d5fc89180867b7  \
#              -Dsonar.qualitygate.wait=true

      - uses: kitabisa/sonarqube-action@master
        with:
          host: https://sonarcloud.io
          login: ${{ secrets.SONAR_TOKEN }}
          projectBaseDir: "src/"
          projectKey: "bhos-qa_l3-sonarcloud-odorT"
          projectName: "bhos-qa_l3-sonarcloud-odorT"


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Junit Tests
          path: build/test-results/test/TEST*.xml
          reporter: java-junit
